Rails.application.routes.draw do
  resources :sensors
  resources :nodes
  #The website root
  root 'index#index'
  #root 'readings#index'

  #Readings routes
  resources :readings, only: [:index, :destroy, :show]

  resources :graphs

  #error log routes
  get '/logs' => 'index#logs'

  #api
   namespace :api do
     namespace :v1 do
       resources :readings, only: [:create]
     end
   end

# **** DONT touch anything below unless you are sure you know what you're doing ****
# Autogenerated by clearance gem, just removed :edit, update

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  # need to use our users controller because we overwrote it
  #Mark - added show/destroy to be able to show all users, removed edit
  resources :users, controller: "users", only: [:create, :show, :destroy, :index, :update] do
        resource :password,
          #Use our controller for the passwords
            controller: "passwords",
            only: [:create,:edit, :update, :new]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  #Use overwritten controller to sign someone up
  get "/sign_up" => "users#new", as: "sign_up"
  #Need to have the email be passed a field passed to the controller so that rails can find the user
  get "/update_password/:email" => "users#edit", :constraints => { :email => /.+@.+\..*/ }, as: "update_user_password"
  get "users/:id/passwords/edit?:token" => "passwords#edit", as: "forgot_password"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
